---

- hosts: hosting
  become: yes
  roles:
    - common
    - docker
    - file_sharing
    - vm

- hosts: nas
  become: yes
  roles:
    - common
    - file_sharing

- hosts: vps
  become: yes
  roles:
    - common

- hosts: dns
  become: yes
  roles:
    - common
    - dns

- hosts: cluster
  become: yes
  roles:
    - common
    - rpi_docker

- hosts: 3d_printer
  become: yes
  roles:
    - common
