---

- hosts: hosting
  become: yes
  roles:
    - common
    - docker
    - file_sharing
    - vm
    - unraid_vm

- hosts: nas
  become: yes
  roles:
    - common
    - file_sharing
    - unraid_vm

- hosts: vps
  become: yes
  roles:
    - common

- hosts: dns
  become: yes
  roles:
    - common
    - dns
    - unraid_vm

- hosts: cluster
  become: yes
  roles:
    - common
    - rpi_docker

- hosts: 3d_printer
  become: yes
  roles:
    - common
    - file_sharing

- hosts: common_only
  become: yes
  roles:
    - common

- hosts: smart_speaker
  become: yes
  roles:
    - common
    - smart_speaker
