---

- hosts: jiri-iris
  become: yes
  roles:
    - common

- hosts: hosting
  become: yes
  roles:
    - common
    - docker
    - file_sharing

- hosts: visual
  become: yes
  roles:
    - common
    - grafana_visual
    - reboot

- hosts: nas
  become: yes
  roles:
    - common
    - file_sharing

- hosts: vps
  become: yes
  roles:
    - common

- hosts: rpi
  become: yes
  roles:
    - common
    - dns
