---

- hosts: hosting
  become: yes
  roles:
    - common
    - docker
    - file_sharing

- hosts: nas
  become: yes
  roles:
    - common
    - file_sharing

- hosts: vps
  become: yes
  roles:
    - common

- hosts: rpi
  become: yes
  roles:
    - common
    - dns
