- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart ntpd archlinux
  service:
    name: ntpd
    state: restarted

- name: restart ntpd debian
  service:
    name: ntp
    state: restarted
