---
- name: Enable pacman color
  ini_file:
    path: /etc/pacman.conf
    allow_no_value: yes
    section: options
    option: Color
  when: ansible_distribution == "Archlinux"

- name: Enable pacman pacman
  ini_file:
    path: /etc/pacman.conf
    allow_no_value: yes
    section: options
    option: ILoveCandy
  when: ansible_distribution == "Archlinux"

- name: Set pacman ParallelDownloads
  ini_file:
    path: /etc/pacman.conf
    value: 5
    section: options
    option: ParallelDownloads
  when: ansible_distribution == "Archlinux"

- name: Enable pacman CheckSpace
  ini_file:
    path: /etc/pacman.conf
    allow_no_value: yes
    section: options
    option: CheckSpace
  when: ansible_distribution == "Archlinux"
