---
- name: Disable the stupid vim mouse integration
  lineinfile:
    dest: "{{ vimrc }}"
    regexp: "^#?autocmd\ BufEnter"
    line: "autocmd BufEnter * set mouse="
    state: present

- name: set yaml indentation to 2
  lineinfile:
    dest: "{{ vimrc }}"
    regexp: "^#?autocmd\ FileType"
    line: "autocmd FileType yaml setlocal shiftwidth=2"
    state: present

- name: download the kuroi color theme
  get_url:
    url: https://raw.githubusercontent.com/aonemd/kuroi.vim/master/colors/kuroi.vim
    dest: /usr/share/vim/vim81/colors/
    mode: 0644
    owner: root
    group: root
  when: ansible_distribution == "Archlinux"

- name: download the simo-zz-2 color theme
  get_url:
    url: https://raw.githubusercontent.com/gvee-s/simo-zz-2/master/colors/simo-zz-2.vim
    dest: /usr/share/vim/vim81/colors/
    mode: 0644
    owner: root
    group: root
  when: ansible_distribution == "Archlinux"

- name: download the blackboard color theme
  get_url:
    url: https://raw.githubusercontent.com/wmvanvliet/vim-blackboard/master/colors/blackboard.vim
    dest: /usr/share/vim/vim81/colors/
    mode: 0644
    owner: root
    group: root
  when: ansible_distribution == "Archlinux"

- name: create the vim syntax folders for all users
  file:
    path: "~{{ item }}/.vim/syntax/"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0755
  loop:
  - jiri
  - ansible
  - root
  when: ansible_distribution == "Archlinux"

  #- name: download the new python syntax for vim
  #  get_url:
  #    url: https://raw.githubusercontent.com/wmvanvliet/vim-blackboard/master/syntax/python.vim
  #    dest: "~{{ item }}/.vim/syntax"
  #    mode: 0644
  #    owner: "{{ item }}"
  #    group: "{{ item }}"
  #  loop:
  #  - jiri
  #  - ansible
  #  - root
  #  when: ansible_distribution == "Archlinux"

- name: set the vim truecolors
  lineinfile:
    dest: "{{ vimrc }}"
    regexp: "^#?set\ termguicolors"
    line: "set termguicolors"
    state: present
  when: ansible_distribution == "Archlinux"

- name: set the vim background
  lineinfile:
    dest: "{{ vimrc }}"
    regexp: "^#?set background"
    line: "set background=dark"
    state: present
  when: ansible_distribution == "Archlinux"

- name: set the vim colorscheme
  lineinfile:
    dest: "{{ vimrc }}"
    regexp: "^#?colorscheme"
    line: "colorscheme blackboard"
    state: present
  when: ansible_distribution == "Archlinux"
