---
- name: Install docker and docker-compose
  package:
    state: present
    name:
    - "docker"
    - "docker-compose"
    - "python-docker"
  tags:
  - docker

- name: Enable docker service
  service:
    name: docker
    state: started
    enabled: yes
  tags:
  - docker

- name: Set vm.max_map_count
  copy:
    content: |
      vm.max_map_count=262144
    dest: /etc/sysctl.d/90-docker.conf
  notify: reload sysctl
  tags:
  - docker

    #- name: Make sure swarm is off
    #  docker_swarm:
    #    state: absent
    #    force: true
    #  tags:
    #  - docker


- name: add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop:
  - jiri
  - ansible
  - root

- name: Create docker swarm
  docker_swarm:
    state: present
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    listen_addr: "{{ ansible_default_ipv4.address }}"
  register: swarm
  when: docker_swarm == "master"
  tags:
  - docker

- name: Join docker swarm
  docker_swarm:
    state: join
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    join_token: "{{ hostvars['lisa.sellerdale.com'].swarm.swarm_facts.JoinTokens.Worker }}"
    remote_addrs: "{{ [hostvars['lisa.sellerdale.com'].ansible_default_ipv4.address] }}"
  when: docker_swarm == "slave"
  tags:
  - docker
