hostname: lisa.santorini.dokoupil.cz
temp_version: "v1"
temp_location: "top_rack"

afp:
  hostname: "lisa"
  announce: false
  domain: "santorini.dokoupil.cz"
  mimic_model: "AirPort7,120"
  admin_group: "jiri"
  hosts_allow: "172.16.32.0/24"
  shares:
    - name: TimeMachine
      path: /mnt/hdd/timemachine
      users: "jiri ansible root nobody"
      timemachine: yes
    - name: Video
      path: /mnt/hdd/video
      users: "jiri ansible root nobody"
      timemachine: no
    - name: General
      path: /mnt/hdd/general
      users: "jiri ansible root nobody"
      timemachine: no
    - name: Music
      path: /mnt/hdd/music
      users: "jiri ansible root nobody"
      timemachine: no
    - name: Torrents
      path: /mnt/ssd/docker/data/transmission_downloads/downloads
      users: "jiri ansible root nobody"
      timemachine: no

nfs:
  shares:
    - name: Video
      path: /mnt/hdd/video
      allowed_range: "172.16.32.0/24"
      mount_options: "rw,sync"
    - name: General
      path: /mnt/hdd/general
      allowed_range: "172.16.32.0/24"
      mount_options: "rw,sync"
    - name: Music
      path: /mnt/hdd/music
      allowed_range: "172.16.32.0/24"
      mount_options: "rw,sync"

dlna:
  name: "Lisa DLNA"
  cache: "/var/cache/minidlna"
  inotify: "yes"
  port: 8200
  log_dir: "/var/log"
  shares:
    - name: Music
      path: /mnt/hdd/music
      type: A
    - name: Video
      path: /mnt/hdd/video
      type: V

samba:
  workgroup: "WORKGROUP"
  name: "lisa"
  announce: true
  mimic_model: "AirPort7,120"
  hosts_allow: "172.16.32."
  wins_support: "yes"
  logs: "/var/log/samba/log.%m"
  log_dir: "/var/log/samba/"
  shares:
    - name: TimeMachine
      path: /mnt/hdd/timemachine
      writable: yes
      browseable: yes
      spotlight: yes
      apple_extensions: yes
      timemachine: yes
    - name: Video
      path: /mnt/hdd/video
      writable: yes
      browseable: yes
      spotlight: yes
      apple_extensions: yes
      timemachine: no
    - name: Music
      path: /mnt/hdd/music
      writable: yes
      browseable: yes
      spotlight: yes
      apple_extensions: yes
      timemachine: no
    - name: General
      path: /mnt/hdd/general
      writable: yes
      browseable: yes
      spotlight: yes
      apple_extensions: yes
      timemachine: no
    - name: Torrents
      path: /mnt/ssd/docker/data/transmission_downloads/downloads
      writable: yes
      browseable: yes
      spotlight: yes
      apple_extensions: yes
      timemachine: no
