hostname: rancher.sellerdale.com
systemd_boot: true
vm: true

docker_swarm: "disabled"
  # either "master", "slave" or "disabled"

afp:
  hostname: "rancher"
  announce: false
  domain: "sellerdale.com"
  mimic_model: "AirPort7,120"
  admin_group: "jiri"
  hosts_allow: "10.85.0.0/24"
  shares:
    - name: General
      path: /mnt/general
      users: "jiri ansible root nobody"
      timemachine: no

nfs:
  shares:
    - name: mnt
      path: /mnt
      allowed_range: "10.85.0.0/24"
      mount_options: "rw,sync"

samba:
  workgroup: "WORKGROUP"
  name: "rancher"
  announce: true
  mimic_model: "AirPort7,120"
  hosts_allow: "10.85.0."
  wins_support: "yes"
  logs: "/var/log/samba/log.%m"
  log_dir: "/var/log/samba/"
  shares:
    - name: General
      path: /mnt/general
      writable: yes
      browseable: yes
      spotlight: yes
      apple_extensions: yes
      timemachine: no
