---
- name: Install TFTP Server Arch
  package:
    state: present
    name:
    - "atftp"
  when: ansible_distribution == "Archlinux"
  tags:
  - share

- name: Install TFTP Server Debian
  package:
    state: present
    name:
    - "atftpd"
  when: ansible_facts['os_family'] == "Debian"
  tags:
  - share

- name: Enable and start the TFTP server
  service:
    name: atftpd
    state: started
    enabled: yes
  tags:
  - share

- name: Create TFTP share directory
  file:
    state: directory
    path: "/srv/atftp"
    mode: 0777
    owner: jiri
    group: jiri
  tags:
  - share

